### ISSUE TITLE
Segfault with -f csv|sqlite

### ISSUE THREAD

**Issue by scop** [client9/misspell#152]
```
$ echo foo | misspell -f sqlite
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4daf97]

goroutine 1 [running]:
log.(*Logger).Output(0x0, 0x2, 0xc42011a0a0, 0x94, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/log/log.go:153 +0x47
log.(*Logger).Println(0x0, 0xc42004bed8, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/log/log.go:188 +0x6a
main.main()
	/home/travis/gopath/src/github.com/client9/misspell/cmd/misspell/main.go:184 +0x6c3
```

```
$ echo foo | misspell -f csv
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4daf97]

goroutine 1 [running]:
log.(*Logger).Output(0x0, 0x2, 0xc420014840, 0x20, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/log/log.go:153 +0x47
log.(*Logger).Println(0x0, 0xc42004bee8, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/log/log.go:188 +0x6a
main.main()
	/home/travis/gopath/src/github.com/client9/misspell/cmd/misspell/main.go:179 +0x1b48
```

**Comment by nnpcYvIVl** [comment]
I'm having the same problem with version 0.3.4.
```
misspell -f csv .
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4ec67e]

goroutine 1 [running]:
log.(*Logger).Output(0x0, 0x2, 0xc042066360, 0x20, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/log/log.go:153 +0x4e
log.(*Logger).Println(0x0, 0xc042085ee8, 0x1, 0x1)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/log/log.go:188 +0x71
main.main()
        /home/travis/gopath/src/github.com/client9/misspell/cmd/misspell/main.go:179 +0x1b4f
```
